import time
from typing import Dict, Optional
from openai import OpenAI

class TextAnalysisApp:
    def __init__(self):
        self.client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key="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",  # Replace with your actual OpenRouter API key
        )
        self.extra_headers = {
            "HTTP-Referer": "https://my-text-analysis-app.com",  # Replace with your site URL
            "X-Title": "Text Analysis App"  # Replace with your site title
        }

    def send_api_request(self, prompt: str) -> Optional[str]:
        """Send request to OpenRouter API and return response content."""
        try:
            completion = self.client.chat.completions.create(
                extra_headers=self.extra_headers,
                extra_body={},
                model="qwen/qwen2.5-vl-32b-instruct:free",
                messages=[
                    {
                        "role": "user",
                        "content": prompt
                    }
                ]
            )
            return completion.choices[0].message.content
        except Exception as e:
            print(f"Error during API request: {e}")
            return None

    def check_plagiarism(self, text: str) -> str:
        """Check if text is AI-generated or human-written."""
        prompt = f"Analyze the following text and determine if it was generated by an AI (e.g., ChatGPT) or written by a human. Provide a clear conclusion and confidence score: {text}"
        response = self.send_api_request(prompt)
        if response:
            return response
        return "Failed to analyze text for plagiarism."

    def check_grammar(self, text: str) -> str:
        """Check text for grammar mistakes and suggest corrections."""
        prompt = f"Perform a detailed grammar check on the following text. List all grammar mistakes and provide corrections: {text}"
        response = self.send_api_request(prompt)
        if response:
            return response
        return "Failed to analyze text for grammar."

    def convert_ai_to_human(self, text: str) -> str:
        """Convert AI-generated text to human-like text."""
        prompt = f"Rewrite the following AI-generated text to sound natural and human-written, maintaining the original meaning: {text}"
        response = self.send_api_request(prompt)
        if response:
            return response
        return "Failed to convert text."

    def display_menu(self):
        """Display the main menu."""
        print("\n" + "="*50)
        print("       Text Analysis Application")
        print("="*50)
        print("1. Check Plagiarism (AI vs Human)")
        print("2. Check Grammar Mistakes")
        print("3. Convert AI Content to Human")
        print("4. Exit")
        print("="*50)

    def run(self):
        """Run the application loop."""
        while True:
            self.display_menu()
            choice = input("Enter your choice (1-4): ").strip()
            
            if choice == "4":
                print("Thank you for using Text Analysis App. Goodbye!")
                break
            
            if choice not in ["1", "2", "3"]:
                print("Invalid choice. Please select 1, 2, 3, or 4.")
                continue
            
            text = input("\nEnter the text to analyze: ").strip()
            if not text:
                print("Error: Text cannot be empty.")
                continue

            print("\nProcessing...")
            time.sleep(1)  # Simulate processing delay for user experience

            if choice == "1":
                result = self.check_plagiarism(text)
                print("\nPlagiarism Check Result:")
                print("-"*50)
                print(result)
            elif choice == "2":
                result = self.check_grammar(text)
                print("\nGrammar Check Result:")
                print("-"*50)
                print(result)
            elif choice == "3":
                result = self.convert_ai_to_human(text)
                print("\nAI-to-Human Conversion Result:")
                print("-"*50)
                print(result)

            input("\nPress Enter to continue...")

def main():
    app = TextAnalysisApp()
    print("Welcome to the Text Analysis Application!")
    print("This tool helps you analyze text for plagiarism, grammar, and AI-to-human conversion.")
    app.run()

if __name__ == "__main__":
    main()


